### ISSUE TITLE
About copyright in license

### ISSUE THREAD

**Issue by akien-mga** [fcazalet/loggot#1]
Hi there,

I noticed your `LICENSE` states:
```
Copyright (c) 2019 Tomek
```

I wonder if this isn't a copy paste mistake? You might well use "Tomek" as pseudonym but given that it's a nickname for Tomasz in Polish and your name seems to be Florian (according to the Git commits), I suppose that's not intentional?

It's the same in your other plugin: https://github.com/fcazalet/godot-version-management/blob/main/LICENSE

**Comment by fcazalet** [comment]
Hi akien,
You are completly right. It is a big copy paste mistake.
Thank you a lot.
I fixed it on the two repositories, main branches.
